// <auto-generated />
namespace Project2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedHasAvatarfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedHasAvatarfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241147454_Added HasAvatar field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
